drop table if exists MEMBER_V2 CASCADE;
create table MEMBER_V2
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    value varchar(255) not null,
    primary key (id)
);


-- Language: sql
-- Path: sql/ddl.sql
drop table if exists FACILITY_TITLE_V1 CASCADE;
create table FACILITY_TITLE_V1
(
    id bigint generated by default as identity,
    title varchar(1023) not null,
    primary key (id)
);

-- Language: sql
-- Path: sql/ddl.sql
-- join으로 FACILITY_TITLE_V1 테이블과 FACILITY_RESERVE_TIME_V1 테이블을 조인하여
-- FACILITY_TITLE_V1 테이블의 title 컬럼과 FACILITY_RESERVE_TIME_V1 테이블의 reserve_time 컬럼을
-- FACILITY_RESERVE_TIME_V1 테이블에 insert
drop table if exists FACILITY_RESERVE_TIME_V1 CASCADE;
create table FACILITY_RESERVE_TIME_V1
(
    id bigint generated by default as identity,
    title varchar(1023) not null,
    user_name varchar(1024) not null,
    reserve_time varchar(1023) not null,
    primary key (id)
);