drop table if exists MEMBER_V2 CASCADE;
create table MEMBER_V2
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    value varchar(255) not null,
    primary key (id)
);


-- Language: sql
-- Path: sql/ddl.sql
drop table if exists FACILITY_TITLE_V1 CASCADE;
create table FACILITY_TITLE_V1
(
    id bigint generated by default as identity,
    title varchar(1023) not null,
    primary key (id)
);